### ISSUE TITLE
不能适配主题背景色

### ISSUE THREAD

**Issue by tcmtom** [zuoez02/siyuan-plugin-webview-flomo#1]
![image](https://github.com/zuoez02/siyuan-plugin-webview-flomo/assets/94541098/91468ab2-c3f1-4479-b11f-73a411062ac0)

是主题的问题还是插件的问题呀

**Comment by zuoez02** [comment]
对应网站无法自动识别思源主题配置的，需要登录之后找到它们自己的配置页面修改亮色或者暗色吧。

这个就是网页套壳而已，不用想太好
