### ISSUE TITLE
希望把dock的添加扩展到思源所有页签

### ISSUE THREAD

**Issue by mozhux** [zuoez02/siyuan-plugin-webview-flomo#11]
如题，希望能在页签右键菜单添加`添加到dock`按钮，然后就可以把页签钉在dock，变相实现打开思源就是首页、随机复习、文档流日记等功能。
![image](https://github.com/zuoez02/siyuan-plugin-webview-flomo/assets/46953371/68c09609-26a2-495b-9e11-bc61c088c904)

另外就是变成dock后，想临时用页签，希望能单独加个新页签打开的快捷键或者按钮，类似edge那样？
![image](https://github.com/zuoez02/siyuan-plugin-webview-flomo/assets/46953371/c6e54cd9-0302-49ec-9026-e41a65f4279e)

**Comment by zuoez02** [comment]
想法挺好，不过感觉不适合放到webapp里，可以做个别的插件实现，我先记录一下需求
