### ISSUE TITLE
cubox 地址问题

### ISSUE THREAD

**Issue by woniuxia** [zuoez02/siyuan-plugin-webview-flomo#14]
大佬 cubox 的地址默认的是国际版的不是国内版的，请问是符合预期的吗？
如果符合预期的话，麻烦插件内简单说明下，我登录了大半天登录不上去。

**Comment by zuoez02** [comment]
符合预期，因为国际版有AI，国内版没AI。你可以自己添加一下，我插件里可以加上名称（国际版）这样

**Comment by zuoez02** [comment]
新版本已经区分了中国版和国际版
