### ISSUE TITLE
网页高度显示不全,只显示一小部分,几乎无法使用

### ISSUE THREAD

**Issue by yongnianliu** [zuoez02/siyuan-plugin-webview-flomo#18]
系统: Win11 x64 专业版本
思源版本:v2.10.10
Web插件版本:v2.5.2
![image](https://github.com/zuoez02/siyuan-plugin-webview-flomo/assets/6042007/79db87ae-dd32-4f6f-8e2a-9e52dbaf81d2)

**Comment by zuoez02** [comment]
查看一下你的主题，可能是主题不兼容的问题

**Comment by yongnianliu** [comment]
![image](https://github.com/zuoez02/siyuan-plugin-webview-flomo/assets/6042007/472326dc-f336-4e37-b8fb-89332b862971)
确实是主题引起的，感谢
