### ISSUE TITLE
右键不能使用

### ISSUE THREAD

**Issue by pisceswb** [zuoez02/siyuan-plugin-webview-flomo#19]
因为右键不能使用，因此不能复制图片png，粘贴入思源笔记中。
直接拖拽图片到思源笔记中，得到的是网络图片，链接容易失效，而且不能OCR。部分网址又不能使用思源笔记的网络图片转本地图片功能。
因此，能否显示原右键菜单，或增加复制图片到剪切板的功能？
谢谢！

**Comment by zuoez02** [comment]
已支持
