### ISSUE TITLE
打开是移动端的尺寸，可以调整吗

### ISSUE THREAD

**Issue by SuperNoobTao** [zuoez02/siyuan-plugin-webview-flomo#2]
<img width="1316" alt="image" src="https://github.com/zuoez02/siyuan-plugin-webview-flomo/assets/16486344/573bb476-fafd-42e2-ab3a-40ff1dd310f5">

**Comment by zuoez02** [comment]
我这复现不出来，是有什么操作可以配置flomo按照移动端展示嘛？

**Comment by zuoez02** [comment]
左上角汉堡菜单点一下，看看什么效果？我看能显示侧边栏

**Comment by SuperNoobTao** [comment]
奇怪了。。。难道就我是这样吗。。
![image](https://github.com/zuoez02/siyuan-plugin-webview-flomo/assets/16486344/514e4e3e-e97d-45f4-8dbe-253b20e68032)

**Comment by SuperNoobTao** [comment]
> 我这复现不出来，是有什么操作可以配置flomo按照移动端展示嘛？

额。这个插件不会就是为了在手机上打开的吧？可能我理解错误了，我是在电脑上打开的，然后插件是移动端的样式
