### ISSUE TITLE
每次重启思源，插件/网页控件就消失了

### ISSUE THREAD

**Issue by maxhytv** [zuoez02/siyuan-plugin-webview-flomo#26]
## 重启前
![image](https://github.com/zuoez02/siyuan-plugin-webview-flomo/assets/60640437/5d8660f5-87f4-4f45-99cc-e37821f32258)
## 重启后
![image](https://github.com/zuoez02/siyuan-plugin-webview-flomo/assets/60640437/3c197a33-5920-4917-9614-73beeca14a1f)

**Comment by zuoez02** [comment]
思源的问题，去思源的仓库提问吧，添加dock后消失

**Comment by zuoez02** [comment]
另外你的思源版本是什么

**Comment by maxhytv** [comment]
> 另外你的思源版本是什么

v2.10.16

**Comment by maxhytv** [comment]
> 另外你的思源版本是什么

好的，我去问问看，目前只有web插件出现这个问题；每次要重新开启一次插件开关，才会出现dock

**Comment by zuoez02** [comment]
v3.4.5 修正这个问题
