### ISSUE TITLE
疑似由于在 `await` 之后添加 dock 导致 Dock 启动的时候没有正常显示

### ISSUE THREAD

**Issue by frostime** [zuoez02/siyuan-plugin-webview-flomo#28]
我发现 reload 的时候 dock 有时候会不显示（常常），怀疑是和这个有关：

见：https://github.com/siyuan-note/siyuan/issues/8375

#26

**Comment by zuoez02** [comment]
估计还是时机的问题，我把addDock从onload挪走到onLayoutReady试试吧

**Comment by zuoez02** [comment]
需要配合思源的问题还是
