### ISSUE TITLE
Docker部署Web版思源提示插件不兼容

### ISSUE THREAD

**Issue by yongnianliu** [zuoez02/siyuan-plugin-webview-flomo#35]
环境: Docker部署思源Web版
思源版本: v3.0.5
插件版本:v3.5.4
![Uploading image.png…]()

很实用的一个插件，在桌面版记录了很多网站，在Web版用不了，希望作者能解决一下，谢谢

**Comment by zuoez02** [comment]
因为确实不兼容，技术上无法解决的问题

**Comment by yongnianliu** [comment]
> 因为确实不兼容，技术上无法解决的问题

好的，感谢回复
