### ISSUE TITLE
一些优化小建议

### ISSUE THREAD

**Issue by Aiviokoo** [zuoez02/siyuan-plugin-webview-flomo#4]
Z佬也许也可以考虑 也可以弄成类似文档树的层级，这样就真成收藏夹了，哈哈（不过没有也还好，看大佬的想法了）
其他的还有这些如果不太麻烦的话，Z佬也可以优化一下，感谢。
![I02TP}1 85AQQ201CJH6UL9](https://github.com/zuoez02/siyuan-plugin-webview-flomo/assets/87182333/413e3b4b-b44f-4253-a1d9-731717897a0a)

**Comment by yanyu2015** [comment]
借楼提一下两个建议：
- 删除那个按钮，能不能点击后邮件删除，不然很容易误触
- 插件目前支持网页刷新功能不？我发现我用的类似滴答清单的一个工具的页面没有及时更新，但用浏览器可以，用思源的插件不知道是都就刷新一次页面呢？

**Comment by Kyrfe** [comment]
也借楼提一下两个建议：

- 希望能移除网页的拼写检查
- 希望能通过右键多开，便于思源分屏浏览

**Comment by zuoez02** [comment]
> 借楼提一下两个建议：
> 
> * 删除那个按钮，能不能点击后邮件删除，不然很容易误触
> * 插件目前支持网页刷新功能不？我发现我用的类似滴答清单的一个工具的页面没有及时更新，但用浏览器可以，用思源的插件不知道是都就刷新一次页面呢？

1. 删除有确认提示框了
2. v3.5.0 支持刷新
