### ISSUE TITLE
remcraft主题下显示不全

### ISSUE THREAD

**Issue by JOYCELEEEEE** [zuoez02/siyuan-plugin-webview-flomo#5]
如图
![image](https://github.com/zuoez02/siyuan-plugin-webview-flomo/assets/89592448/a9e785a3-83e7-4464-b229-a1f4cdfdb864)

不知道大佬能否抽空优化一下呢，您的插件对我帮助非常大，感谢您的贡献~

**Comment by zuoez02** [comment]
主题的问题，建议自己添加CSS代码片段

.layout-tab-container>.fn__flex-1>.fn__flex-1 {
  min-height: 100% !important;
}

**Comment by JOYCELEEEEE** [comment]
好的，谢谢大佬！


发件人: Luto ***@***.***>
发送时间: 2023年5月26日 14:23
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [zuoez02/siyuan-plugin-webview-flomo] remcraft主题下显示不全 (Issue #5)


主题的问题，建议自己添加CSS代码片段

.layout-tab-container>.fn__flex-1>.fn__flex-1 {
min-height: 100% !important;
}

―
